#!/bin/sh

# Format code
npx -c yarn format

# Check TypeScript types
npx -c yarn tsc --noEmit

# Build the project
npx -c yarn build
git add public/sitemap.xml
git add public/sitemap.json

# Run lint-staged to lint only staged files
npx lint-staged