name: CI/CD

on:
  push:
    branches:
      - development
      - stage
      - main
  pull_request:
    branches:
      - development
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_URL: 'https://api.dev.goods2load.com/'
      NEXT_PUBLIC_CLIENT_URL: 'http://localhost:3000'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
